### ISSUE TITLE
Implement Svelte SSR by Tuono Rust

### ISSUE THREAD

**Issue by jeromeleong** [Valerioageno/tuono#1]
Hi @Valerioageno, I noticed there's an interest in implementing Svelte SSR using Tuono Rust. I can assist in creating a pull request for this feature. Let's discuss the requirements and how we can proceed with the implementation.

**Comment by Valerioageno** [comment]
Hi @jeromeleong, Tuono specifically is a (early stages) React fullstack framework so Svelte is not included here. 

That said [ssr-rs](https://github.com/Valerioageno/ssr-rs) is the crate that holds the logic to perform the server side rendering so a Svelte implementation would be better to be implemented there. 

I'm not familiar with Svelte but I think the logic should be pretty similar as the React one. In my opinion the best would be just to create an example project in the `ssr-rs/examples/` folder, take a snapshot of the Svelte `bundle.js` and create an integration test [here](https://github.com/Valerioageno/ssr-rs/tree/main/tests) (as you can see in the assets folder there are already the react bundles).

In case there is the need to update the V8 logic I'm available for improvements.

Thanks for the interest. Let me know if I can be of any help!

**Comment by Valerioageno** [comment]
Closing this issue because stale. Feel free to reopen it in the [ssr_rs](https://github.com/Valerioageno/ssr-rs) repo which is more correct for that improvement.
