### ISSUE TITLE
Repo maintenance: enforce format on all supported files

### ISSUE THREAD

**Issue by marcalexiei** [Valerioageno/tuono#108]
Right now some files (like `json`, `yml` and `yaml`) are not automatically checked and formatted.

`prettier` supports formatting for all those files.
I would like also adding `md` / `mdx` to the list.

How about adding formatting checks for all these files using `prettier`?

**Comment by Valerioageno** [comment]
What are the checks about? Yeah I think it is a nice improvement indeed!

**Comment by Valerioageno** [comment]
No worries. It is a great addition in my opinion! Thanks for bringing this up!
