### ISSUE TITLE
🎉 Announcement: Discord server

### ISSUE THREAD

**Issue by Valerioageno** [Valerioageno/tuono#112]
Hi all,

the project is growing fast! 🚀 

I'm creating a discord server where we can quickly discuss about the project. [Here the link](https://discord.gg/khQzPa654B).  

For now we only have three channels:

**#general** for general discussions about Tuono
**#support** for getting fast support on Tuono development and contribution
**#community-suggestions** for suggesting improvements related to the community management

Feel free to join :)

**Comment by uoussefqadry** [comment]
![Image](https://github.com/user-attachments/assets/6d93bb08-c2e0-4d45-85ef-93be0fe878ad)

**Comment by Valerioageno** [comment]
What link did you use?
