### ISSUE TITLE
[Feature request]: Better error handling when target port is already in use

### ISSUE THREAD

**Issue by myanvoos** [Valerioageno/tuono#123]
### Is your feature request related to a problem? Please describe.

Currently Tuono's default target port is 3000. If that port is already in use and we try to run `tuono dev` we get the following error:

![image](https://github.com/user-attachments/assets/b6f58849-45e8-44ea-9259-83a8527868ff)

### Describe the solution you'd like

Tuono can try continuously searching for the next available port to use and stopping when it finds the next available one, instead of throwing an error.

**Comment by Valerioageno** [comment]
As a quick improvement, though, I'd gracefully close the `tuono` CLI process with a meaningful message in case one of the two ports are already taken.

**Comment by myanvoos** [comment]
> Hey @myanvoos, thanks for raising this. Definitely, we should improve the way we handle such case.
> 
> > Note: actually during development there are two open ports: `3000` for the rust server + `3001` for the vite server.
> 
> Personally, I wouldn't leave to the host machine (or to tuono itself) the duty of finding an available port since there are too many processes involved which make it error-prone IMHO. I'd rather allow the user to specify the desired port(s) using the (not available yet) `tuono.config.ts` file or a flag in the CLI like `tuono dev --port 4000`.
> 
> WDYT?
> 
> Tagging here also @marcalexiei for visibility since we already started discussing a `tuono.config.ts` file.

I like the idea of a tuono.config.ts file! And the CLI flag too, although it might not be clear at first glance whether we're specifying the Rust server port or the Vite port. Maybe `tuono dev --port x` can specify the Rust port and as a convention, the Vite port can be at `x+1`?

I'll have a go at implementing the CLI closing process in my fork^^

**Comment by Valerioageno** [comment]
> Maybe tuono dev --port x can specify the Rust port and as a convention, the Vite port can be at x+1?

Yes!

Waiting for you PR then! :)

**Comment by Valerioageno** [comment]
Let's create also a discussion - maybe on Discord - about the new `tuono.config.ts` and let's define a priority based roadmap for it
