### ISSUE TITLE
[Bug]: Error when running tuono run dev

### ISSUE THREAD

**Issue by adityapandeydev** [Valerioageno/tuono#150]
### Description

I am not yet sure if the problem is my system or not, but I thought the best place to know will be here. I am sorry if this was a time waste and I will delete the issue. But the problem I am facing is upon running tuono dev (I ran the command just after doing npm install without making any changes in the default code) I am getting this error (I have uploaded the pictures).
![image](https://github.com/user-attachments/assets/7e010be0-530c-4376-a44b-5fde7e47f02e)
![image](https://github.com/user-attachments/assets/a938af14-d93a-4b4b-b906-699dfe5ae35f)

### Expected behaviour

I just expected to see it working, like you normally run npm run dev just after creating a new project.

### How to reproduce

I ran the tuono dev command immediately after creating the project and running the npm install command.

### Tuono version

0.14.1

### OS

Windows

### Node version

20.13.1

### Rust version

1.79.0

### Node Package Manger version

10.8.3

**Comment by Valerioageno** [comment]
Looks like you don't have installed the npm dependencies. What node package manager are you using?

**Comment by Valerioageno** [comment]
Thanks for reporting. That definitely is a bug with Windows.

**Comment by Valerioageno** [comment]
Hey @adityapandeydev, thanks for reporting it. The fix has just been published. You can update `tuono`by running

```sh
cargo install tuono@0.14.3
```

Let me know if you will find something broken 😄

**Comment by adityapandeydev** [comment]
Unfortunately I am still finding the same error. I installed the updated version as you said.
![image](https://github.com/user-attachments/assets/c4417025-9960-40a8-8f0b-3bfb473476d7)
![image](https://github.com/user-attachments/assets/7f3eb9d0-b312-4161-b722-9e51a4bee961)
![image](https://github.com/user-attachments/assets/fee81c7d-83e2-4820-aab2-1eb8c053f500)
Also the name of the project might be the same as before but I deleted the project and created a new one with the same name, so all the node modules and everything is fresh.
I also tried to create a new project in a different directory to see if this might be a caching issue, i still faced the same error but made a new discovery (don't know if you already knew this) but when this error comes the localhost port is getting occupied, because when I created the project in the new directory and ran the tuono dev command I was getting a different error which was [port 3001 is already in use], I had to ctrl + c the terminal of the previous project and then when I again ran I started getting the same error.

**Comment by Valerioageno** [comment]
Mmmm. This seems a problem with the V8 build...

What is your PC cpu?

**Comment by adityapandeydev** [comment]
17-12700H
I use a laptop

**Comment by Valerioageno** [comment]
Gotcha. Could you please copy paste the whole error log?

**Comment by adityapandeydev** [comment]
error: failed to run custom build command for `v8 v129.0.0`

Caused by:
  process didn't exit successfully: `D:\Aditya\Projects\NotSure\target\debug\build\v8-b2af412007e8ea6b\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=CXXSTDLIB
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=RUSTY_V8_SRC_BINDING_PATH
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rerun-if-env-changed=DISABLE_CLANG
  cargo:rerun-if-env-changed=EXTRA_GN_ARGS
  cargo:rerun-if-env-changed=PRINT_GN_ARGS
  cargo:rerun-if-env-changed=CARGO_ENCODED_RUSTFLAGS
  cargo:rustc-link-lib=static=rusty_v8
  cargo:rustc-link-lib=dylib=winmm
  cargo:rustc-link-lib=dylib=dbghelp
  cargo:rustc-link-lib=dylib=msvcprt
  lockfile: "D:\\Aditya\\Projects\\NotSure\\target\\debug\\build\\v8.fslock"
  Creating symlink "D:\\Aditya\\Projects\\NotSure\\target\\debug\\gn_root" to "C:\\Users\\AdityaPandey\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\v8-129.0.0"
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }

  --- stderr
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  thread 'main' panicked at C:\Users\AdityaPandey\.cargo\registry\src\index.crates.io-6f17d22bba15001f\v8-129.0.0\build.rs:847:17:
  Failed to create symlink
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'tokio-runtime-worker' panicked at tokio-runtime-workerC:\Users\AdityaPandey\.cargo\registry\src\index.crates.io-6f17d22bba15001f\watchexec-supervisor-3.0.0\src\job\task.rs' panicked at :C:\Users\AdityaPandey\.cargo\registry\src\index.crates.io-6f17d22bba15001f\watchexec-supervisor-3.0.0\src\job\task.rs54::5417:
:all branches are disabled and there is no else branch17
:
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
all branches are disabled and there is no else branch

**Comment by Valerioageno** [comment]
Thanks you. I'll let you know soon

**Comment by Valerioageno** [comment]
Could you check that your device is enabled for the development mode? https://github.com/denoland/rusty_v8/issues/1563

**Comment by adityapandeydev** [comment]
Developer mode wasn't enabled, it's working after enabling it. Sorry for causing any inconvenience.

**Comment by Valerioageno** [comment]
No problem. That is something useful to add to the documentation indeed!
