### ISSUE TITLE
[Bug]: Not using all the ApplicationState struct fields in the tuono_lib::handler as arguments gives me an error.

### ISSUE THREAD

**Issue by ma13gagan** [Valerioageno/tuono#170]
### Description

Hey, the docs mention that the fields in the ApplicateState struct are optional. But When I don't use all the fields in tuono_lib::handler, it gives me an error.

![image](https://github.com/user-attachments/assets/fe7ddeac-3f81-4864-b858-0ae68779fc3b)

![image](https://github.com/user-attachments/assets/52136f55-0b73-4d33-aa21-cd95b1239ee5)

![image](https://github.com/user-attachments/assets/8fc9c600-c0df-4e2b-b661-1cd5a82aacdd)

### Expected behaviour

As mentioned in the docs, the ApplicationState arguments should be optional.

### How to reproduce

I cloned the tutorial and added the new fields in the ApplicationState struct.

**Comment by Valerioageno** [comment]
Hi @ma13gagan, the bug should have been fixed. To test it just install the new Tuono version `0.14.4` in your `Cargo.toml` file.
Consider also to update it in `package.json` and to install the latest cli `cargo install tuono@0.14.4`.
