### ISSUE TITLE
Documentation: prove contributing page adding step by step guide to setup the project

### ISSUE THREAD

**Issue by marcalexiei** [Valerioageno/tuono#91]
I'm setting up the project to work on #84.

I cloned the repository and I have run `pnpm install`.
After that I have encountered 2 problems:

### 1. `apps/documentation` types not resolved on VSCode
on `apps/documentation` files I'm not able to have import resolved correctly in the editor:

<img width="1006" alt="vs-code-resolve-errors" src="https://github.com/user-attachments/assets/496cb196-9172-4ef3-8312-15a26ade19da">

> [!NOTE]
> When running `lint` or `types` task from the `CLI` no error is present.
> I can work by running CLI commands but I found out a little strange that the editor is not behaving the same.
> It might be a VSCode issue, but I'm just wondering if you have a local setup or something else I might missed that can solve the issue.

### 2. `dev` task loop

Running `pnpm dev`  causes a loop:

```text
tuono-fs-router-vite-plugin:dev: 
tuono-fs-router-vite-plugin:build: cache miss, executing 552cb6325ef9d96f
tuono-fs-router-vite-plugin:dev: cache miss, executing 4361ae84ef2c11b2
tuono-fs-router-vite-plugin:build: 
tuono-fs-router-vite-plugin:dev: 
tuono-fs-router-vite-plugin:dev: 
tuono-fs-router-vite-plugin:dev: > tuono-fs-router-vite-plugin@0.12.0 dev /Users/marcalexiei/development/tuono/packages/fs-router-vite-plugin
tuono-fs-router-vite-plugin:dev: > vite build --watch
tuono-fs-router-vite-plugin:dev: 
tuono-fs-router-vite-plugin:build: 
tuono-fs-router-vite-plugin:build: > tuono-fs-router-vite-plugin@0.12.0 build /Users/marcalexiei/development/tuono/packages/fs-router-vite-plugin
tuono-fs-router-vite-plugin:build: > vite build
tuono-fs-router-vite-plugin:build: 
tuono-fs-router-vite-plugin:dev: cache miss, executing 87911e2c75a3e2d2
tuono-fs-router-vite-plugin:build: cache miss, executing 383aa3afd2063cef
```

<details>
<summary>Logs screenshot</summary>

<img width="1044" alt="build loop screenshot" src="https://github.com/user-attachments/assets/d5df3477-349b-4ec0-a825-c0704e9b9d98">

</details>

---

### System information

```text
  System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M3
    Memory: 88.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
```

---

It might be worth to create a step by step setup guide on the [contributing page of the documentation site](https://tuono.dev/documentation/contributing) with the list of the commands to setup all dependencies, build and run tests to check that everything in the project is working properly? 
Since you have told me you are working on the server implementation when we resolve these issues I can take care of it.

**Comment by Valerioageno** [comment]
Thanks for sharing. 
1. Did you run `pnpm install` inside the `apps/documentation` folder (optionally `pnpm install --ignore-workspace`)? This might be the issue, since the documentation doesn't use the workspace dependencies.
2. That's interesting. I'll take a look and, I'll let you know.
3. Agree on extending the contributing page!

> Note: I'm working on the server side but that doesn't impact the typescript build. The server implementation is mostly made using Rust.

**Comment by Valerioageno** [comment]
[This](https://github.com/Valerioageno/tuono/pull/92) should fix the `pnpm dev` loop. Could you please check it on you end?

**Comment by marcalexiei** [comment]
With the resolution of #92 I should have everything I need to write the setup guide in the contributing page.
If you wish you can assign this issue to me and I'll link it to the PR with the contribution page update (and I won't forget about it).
I'll try to make it and #84 in the upcoming days.

Thanks again for the quick turnaround.

**Comment by Valerioageno** [comment]
That's great! Done.
Thanks for the help! Really appreciated!

**Comment by Valerioageno** [comment]
Something that might be useful to mention in the contribution page:
In my setup, I put the following alias in my `.bashrc` config:

```
alias t="/path-to-folder/tuono/target/debug/tuono"
```
In this way, it is easier testing the Tuono's CLI outside the project folder.
