### ISSUE TITLE
Repo Maintenance: adding `apps/documentation` to `pnpm` workspaces

### ISSUE THREAD

**Issue by marcalexiei** [Valerioageno/tuono#95]
`apps/documentation` right now is ignored by root workspace setup so it requires a "standalone" pnpm install.   

I think that we can add this folder to the workspaces by:
- using `npm:tuono@{{version}}` notation to explicit that in these folder `tuono` must be downloaded from `npm` registry
- change the package name to avoid clash with the workspaces inside `packages` folder
   ```diff
   + "name": "tuono-documentation",
   - "name": "tuono",
   ```

---

### Pros

1. avoid duplication of some dev configuration / devDependencies from the root package (e.g.: ESLint) 
2. simplify project setup procedure (no need to write about separate `pnpm install` in different directories).
3. user can run check on local machine from the root without having to navigate across folders via file explorer or CLI.
    e.g.: I created #93 and format checks failed on `apps/documentation` folder on [CI run](https://github.com/Valerioageno/tuono/actions/runs/11811551359)

**Comment by Valerioageno** [comment]
I didn't know we could add it to the workspace that way! It seems perfect to me. 

The goal was exactly to use the published library in order to avoid annoying fix in case of breaking changes.

Sounds good to me!
